spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cdmaths
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true
    format_sql: true

    defer-datasource-initialization: true
  # mode: never or always pour charger les données apres création des tables et contraintes
  sql:
    init:
      mode: never

jwt:
  signing:
    key: 72357538782F4125442A472D4B6150645367566B597033733676397924422645
